name: CI-e2e

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        test: [1, 2, 3, 4]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          BUILD_INCLUDE_LOCALES: ${{ startsWith(github.head_ref, 'i18n/') }}
      - name: Test ${{ matrix.test }}
        run: npm run ci:e2e
        env:
          CI: true
          CI_SHARD_INDEX: ${{ matrix.test }}
          CI_SHARD_TOTAL: 4
