name: i18n-update-notify

on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.sender.login != 'github-actions[bot]' && !startsWith(github.head_ref, 'i18n/')
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Create comment on PR
      uses: actions/github-script@v6
      with:
        script: |
            const commentBody = `## i18n Actions
            Source PR has been merged into the default branch.

            Maintainers can comment \`.i18n-update-push\` to trigger the i18n update workflow and push the changes to Lokalise.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
